
name: 'materialize_dbt_utils_dbt_utils_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
  dbt_utils_dispatch_list:
    - materialize_dbt_utils
    - dbt_utils_integration_tests

models:
  # More info about disabled tests: https://github.com/MaterializeInc/materialize-dbt-utils/issues/7
  dbt_utils_integration_tests:
    cross_db_utils:
      # Materialize doesn't support current_timestamp() in static queries
      test_current_timestamp:
        +enabled: false
      test_current_timestamp_in_utc:
        +enabled: false
      # Materialize does not currently support md5
      # See: https://github.com/MaterializeInc/materialize/issues/4461
      test_hash:
        +enabled: false
    sql:
      # Materialize does not currently support md5
      # See: https://github.com/MaterializeInc/materialize/issues/4461
      test_surrogate_key:
        +enabled: false
