name: materialize_dbt_utils_dbt_utils_integration_tests
version: '1.0'
config-version: 2

profile: integration_tests

dispatch:
  - macro_namespace: dbt_utils
    search_order: [materialize_dbt_utils, dbt_utils_integration_tests, dbt_utils]

models:
  dbt_utils_integration_tests:
    datetime:
      # Tested by test_date_spine_override.
      test_date_spine:
        +enabled: false
    schema_tests:
      # Tested by test_recency_override.
      test_recency:
        +enabled: false
