name: CI
on:
  push:
    branches: main
    tags: "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup
        run: |
          pip install dbt-materialize==1.4.0
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          config:
              send_anonymous_usage_stats: False
              use_colors: True

          integration_tests:
            outputs:
              materialize:
                type: materialize
                threads: 1
                host: localhost
                port: 6875
                user: materialize
                password: ignored
                dbname: materialize
                schema: public
          EOF
      - name: Test dbt_utils
        run: make test-materialize
        working-directory: integration_tests/dbt_utils
      - name: Test dbt_audit_helper
        run: make test-materialize
        working-directory: integration_tests/dbt_audit_helper
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

    services:
      materialized:
        image: materialize/materialized:v0.43.0
        ports: ["6875:6875","6878:6878"]
